# Generated by Django 5.1.3 on 2024-11-09 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0006_remove_feedbackprocess_reviewer_review_reviewer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackprocess",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
